# Generated by Django 4.1.7 on 2023-03-13 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_oficialia', models.CharField(max_length=15, verbose_name='Número de Oficialia')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número de serie')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo_i', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('f_factura', models.DateField(blank=True, verbose_name='Fecha de factura')),
                ('n_factura', models.CharField(blank=True, max_length=10, verbose_name='Número de factura')),
                ('orden_c', models.CharField(blank=True, max_length=8, verbose_name='Orden de compra')),
                ('proveedor_c', models.CharField(blank=True, max_length=25, verbose_name='Proveedor')),
                ('centro_c', models.CharField(blank=True, max_length=6, verbose_name='Centrocosto')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionario')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Lugar')),
            ],
        ),
    ]
